### ISSUE TITLE
Slow refresh of home screen 3.64 build 10

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#10]
Sherry from Creature Comforts in AZ if reporting that when her team is bringing the iPhone app forward from being in the background that the Home screen says " Updating Visit information" and when the disappears the app freezes. They try scrolling or click on something and they get nothing. They end out having the Force Close the app and log in again.

**Comment by teddyhoo** [comment]
That is probably because they do not have data access while bringing it forward. I will adjust so that if the network request is unavailable it will use the previous information. If this occurs with people, to be sure that this is the issue (I have experienced and the issue was when there was no connex) have them try to login to LeashTime.com on the browser. If they can login, then it is not a data connex issue.

**Comment by teddyhoo** [comment]
I have logged in three different sitter profiles for AZ Creature Comforts repeatedly cycling back and foreground from list view, from details view. I turned off connection to Internet, turned on, etc...

**Comment by jodsmithLT** [comment]
I am able to reproduce the slow refresh in low connectivity areas. If I give it time, like a minute it comes back up just fine.  It needs some patience, but at the same time, I am sure they just assume it's frozen?

**Comment by teddyhoo** [comment]
In the testflight build i put up recently, try to reproduce. I have set a timeout of 10.0 seconds instead of 30.0 seconds. This should terminate the connection if it proves to be slow.

**Comment by jodsmithLT** [comment]
I have not seen this issue in the new version 3.65 b1
