### ISSUE TITLE
Visit Report Reported sent, but not received on server

### ISSUE THREAD

**Issue by mattleashtime** [teddyhoo/IOS-Sitter-Mobile#18]
LEASHTIME IOS 11 / ver: 3.65 / build:1
https://leashtime.com/support/admin/admin_ticket.php?track=N4L-AL1-LSGN
(#20126) Comment from Sandy Getchell-White

User sandygw submitted a visit report for visit #84982 (9/26 7a-9a Shelley Smith) with:

note
photo
two mood buttons

App reported the visit report was sent, but no email was sent and no VR request appeared on the Home page.  Settings for client are:

Arrival Time: Use the System Default (= NO)
Completion Time: Use the System Default (= NO)
Visit Note: YES
Mood Buttons: YES
Pet Photo: YES
Map of Route: NO
Create Notifications on Home Page when Enhanced Visit Reports are submitted YES

On the server, ONLY the following was received for that visit:

arrived_recd: 2018-09-26 08:15:57
completed_recd: 2018-09-26 08:57:10
native: IOS
visitmapcacheid: 1646

Oddly, the
 mapshot (https://leashtime.com/appointment-map.php?id=84982) shows 5 points, but the received coordinates include only the arrival and completion locations-- no MV coords: (https://leashtime.com/visit-map.php?id=84982&showcoords=1)

![purrfectmaps](https://user-images.githubusercontent.com/41804552/46222861-a4239d00-c31f-11e8-9189-8a34de504570.jpg)

UPDATE: similar problem reported for the same client, same sitter on 9/28.

**Comment by teddyhoo** [comment]
The sitter can login again and go to the visit for which visit report was not sent. Tap the envelope icon again and it will resend the visit report. If the sitter does it from their home or where they know they have an internet connection, and if the visit report arrives, then we can reasonably conclude that this is a failed transmission when they do it live.

The mapsnapshot having five points is good clue. The mapsnapshot is created on the phone from the gathered points. However, since the additional 3 points did not arrive, it means the request failed to transmit. 

Now, I wonder if the sitter did not put a note in or put a funny character in the note. I think the visit report is failing without regard to network conditions. Something about the construction of the note.

**Comment by mattleashtime** [comment]
Here is a summary of the situation as I understand it (see https://leashtime.com/support/admin/admin_ticket.php?track=N4L-AL1-LSGN)

I sent Sandy instructions to re-send and report the results.

On the 9/28 visit she did NOT try to send a note or picture.
On 9/26 and 9/27 she DID send photo and mood buttons.
On 9/28 she reported that sh tried to re-send 9/27's report but there was no Send button.
Somehow 5 minutes later she re-sent the 9/27 report, which went through, except for the photo.
(Confirmed: 3 mood buttons and the following note appear for the 9/27 visit)

============
Everyone has eaten and got their meds.  Biggest challenge was getting Bowden to eat the pill pocket-finally accomplished by isolating Hyundai your bedroom!!
Having fun
============

**Comment by teddyhoo** [comment]
This is going to be grouped with photo not upload bug. They are related in that there is not failover and that is all being addressed across the board for all requests.
